apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../labeltransformer
patches:
- patch: |-
    - op: add
      path: /labels/env
      value: "dev"
  target:
    kind: LabelTransformer
